#!/usr/bin/env python3
"""Apply the CoinJoin USB extension to a Krux source checkout.

Usage: apply.py /path/to/krux    (the repo root, containing src/krux/)

Copies the extension package into the tree, installs the minimal extension
registry (if the checkout doesn't already have the upstream hooks), records
the extension as installed, and — only when the upstream Sign-menu hook is
absent — applies a small fallback patch to home.py. Idempotent.
"""
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
EXT_NAME = "coinjoin"

_INSTALLED_TEMPLATE = '''"""Extensions applied to this build. Generated by an extension's apply.py."""
EXTENSIONS = %r
'''

# Fallback: appends installed extensions' entries to the Sign submenu without
# needing a top-level import. Anchored on the stock message entry.
_HOME_ANCHOR = "                (t(\"Message\"), self.sign_message),\n            ],"
_HOME_PATCHED = (
    "                (t(\"Message\"), self.sign_message),\n"
    "            ]\n"
    "            + __import__(\"krux.extensions\", fromlist=[\"x\"])"
    ".sign_menu_entries(self.ctx),"
)


def _krux_pkg(root):
    for candidate in (os.path.join(root, "src", "krux"), os.path.join(root, "krux")):
        if os.path.isdir(candidate):
            return candidate
    sys.exit("Could not find krux/ package under %s" % root)


def copy_extension(krux_pkg):
    src = os.path.join(HERE, "src", "krux", "extensions", EXT_NAME)
    dst = os.path.join(krux_pkg, "extensions", EXT_NAME)
    if os.path.exists(dst):
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    print("copied extension -> %s" % dst)


def install_registry(krux_pkg):
    ext_dir = os.path.join(krux_pkg, "extensions")
    os.makedirs(ext_dir, exist_ok=True)
    init_path = os.path.join(ext_dir, "__init__.py")
    if not os.path.exists(init_path):
        shutil.copyfile(
            os.path.join(HERE, "upstream-hooks", "extensions__init__.py"), init_path
        )
        print("installed extension registry -> %s" % init_path)
    else:
        print("extension registry already present (upstream hooks)")


def record_installed(krux_pkg):
    path = os.path.join(krux_pkg, "extensions", "_installed.py")
    installed = []
    if os.path.exists(path):
        ns = {}
        with open(path) as f:
            exec(f.read(), ns)  # trusted, build-time
        installed = list(ns.get("EXTENSIONS", []))
    if EXT_NAME not in installed:
        installed.append(EXT_NAME)
    with open(path, "w") as f:
        f.write(_INSTALLED_TEMPLATE % installed)
    print("recorded installed extensions: %s" % installed)


def patch_home_menu(krux_pkg):
    home = os.path.join(krux_pkg, "pages", "home_pages", "home.py")
    if not os.path.exists(home):
        print("WARNING: home.py not found; wire the Sign menu manually")
        return
    with open(home) as f:
        text = f.read()
    if "sign_menu_entries" in text:
        print("Sign-menu hook already present")
        return
    if _HOME_ANCHOR not in text:
        print(
            "WARNING: could not find the Sign submenu anchor in home.py.\n"
            "  Add `+ extensions.sign_menu_entries(self.ctx)` to the sign() "
            "submenu list manually (see upstream-hooks/home_hook.md)."
        )
        return
    with open(home, "w") as f:
        f.write(text.replace(_HOME_ANCHOR, _HOME_PATCHED, 1))
    print("applied fallback Sign-menu hook -> %s" % home)


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    krux_pkg = _krux_pkg(sys.argv[1])
    copy_extension(krux_pkg)
    install_registry(krux_pkg)
    record_installed(krux_pkg)
    patch_home_menu(krux_pkg)
    print("done. Build and flash the Krux as usual.")


if __name__ == "__main__":
    main()
